### PR TITLE
Fix #101 again

### LINKED ISSUE #101: 0.6: ERROR: GitError(Code:ENOTFOUND, Class:Tree, the path '0.1.0' does not exist in the given tree)
```julia
julia> using PkgDev

julia> PkgDev.publish()
WARNING: cat{T <: GitObject}(repo::GitRepo, ::Type{T}, object::AbstractString) is deprecated, use cat(repo, object) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] cat(::Base.LibGit2.GitRepo, ::Type{Base.LibGit2.GitBlob}, ::String) at ./deprecated.jl:51
 [3] (::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String})(::Base.LibGit2.GitRepo) at /Users/solver/.julia/v0.6/PkgDev/src/entry.jl:80
 [4] with(::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:576
 [5] publish(::String, ::String) at /Users/solver/.julia/v0.6/PkgDev/src/entry.jl:64
 [6] publish() at /Users/solver/.julia/v0.6/PkgDev/src/PkgDev.jl:70
 [7] eval(::Module, ::Any) at ./boot.jl:235
 [8] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [9] macro expansion at ./REPL.jl:97 [inlined]
 [10] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
ERROR: GitError(Code:ENOTFOUND, Class:Tree, the path '0.1.0' does not exist in the given tree)
Stacktrace:
 [1] macro expansion at ./libgit2/error.jl:99 [inlined]
 [2] Base.LibGit2.GitObject(::Base.LibGit2.GitRepo, ::String) at ./libgit2/repository.jl:127
 [3] cat at ./libgit2/libgit2.jl:479 [inlined]
 [4] cat(::Base.LibGit2.GitRepo, ::Type{Base.LibGit2.GitBlob}, ::String) at ./deprecated.jl:53
 [5] (::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String})(::Base.LibGit2.GitRepo) at /Users/solver/.julia/v0.6/PkgDev/src/entry.jl:80
 [6] with(::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:576
 [7] publish(::String, ::String) at /Users/solver/.julia/v0.6/PkgDev/src/entry.jl:64
 [8] publish() at /Users/solver/.julia/v0.6/PkgDev/src/PkgDev.jl:70
```

### PR DESCRIPTION
**Pull request by simonbyrne**
#141 made some changes, however I forgot that `content` has different error handling behaviour than `cat`. This is a bit of a kludge, but hopefully should fix #101 again.

### CODE REVIEW

File: src/entry.jl [hunk 1]
```diff
@@ -73,8 +73,17 @@ function publish(branch::AbstractString, prbranch::AbstractString="")
...
             pkg, ver = m.captures; ver = VersionNumber(ver)
             sha1 = readchomp(joinpath(metapath,path))
-            old = LibGit2.content(LibGit2.GitBlob(repo, "origin/$branch:$path"))
-            old !== nothing && old != sha1 && throw(Pkg.PkgError("$pkg v$ver SHA1 changed in METADATA – refusing to publish"))
+            try
+                old = LibGit2.content(LibGit2.GitBlob(repo, "origin/$branch:$path"))
+                if old != sha1
+                    throw(Pkg.PkgError("$pkg v$ver SHA1 changed in METADATA – refusing to publish"))
+                end
+            catch e
```
Comment (tkelman) [inline src/entry.jl]: this is exactly what I meant by
> we should avoid needing try catches everywhere if the new api is going to throw in a bunch of expected situations

is there an error code or anything? this will silently swallow all GitErrors, including unexpected ones that should still be fatal.

Comment (simonbyrne) [reply src/entry.jl]: I agree, but this is basically duct tape at this stage. I've tweaked this a bit to be more specific.
